name: DeclarativeRequests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        xcodebuild test \
          -scheme DeclarativeRequests-Package \
          -destination 'platform=macOS' \
          -resultBundlePath TestResults.xcresult
          -quiet
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
        show-passed-tests: false
      if: failure()
